const arabicCopy: Record<string, string> = {
  Overview: "نظرة عامة",
  Patients: "المرضى",
  "Today's rounds": "جولات اليوم",
  "Clinical copilot": "المساعد السريري",
  Interventions: "التدخلات",
  "Medication review": "مراجعة الأدوية",
  Reconciliation: "المصالحة الدوائية",
  Alerts: "التنبيهات",
  "Drug information": "معلومات الأدوية",
  Calculators: "الحاسبات السريرية",
  Guidelines: "الإرشادات",
  "Training hub": "مركز التدريب",
  "Clinical logbook": "السجل السريري",
  Cases: "الحالات",
  Questions: "الأسئلة",
  Progress: "التقدم",
  "Cloud account": "الحساب السحابي",
  "Cloud medication review": "مراجعة دوائية سحابية",
  "Medication review record": "سجل مراجعة الدواء",
  "Clinical documentation": "التوثيق السريري",
  "SOAP note & intervention log": "ملاحظة SOAP وسجل التدخل",
  "Cloud cases": "الحالات السحابية",
  "Supabase clinical case records": "سجلات الحالات السريرية في Supabase",
  "Student training": "تدريب الطالب",
  "Adaptive therapeutics program": "برنامج العلاج الدوائي التكيفي",
  "Good morning": "صباح الخير",
  "Workspace": "مساحة العمل",
  "Learning & tools": "التعلم والأدوات",
  "Hospital intelligence": "ذكاء المستشفى",
  "Sign in": "تسجيل الدخول",
  "Create account": "إنشاء حساب",
  "Reset password": "إعادة تعيين كلمة المرور",
  "Sign in to enable Supabase sync.": "سجّل الدخول لتفعيل مزامنة Supabase.",
  "Signed in; cloud sync is available.": "تم تسجيل الدخول؛ المزامنة السحابية متاحة.",
  "Account created. Check your email if confirmation is enabled.": "تم إنشاء الحساب. تحقق من بريدك إذا كان التأكيد مفعّلًا.",
  "Authentication failed": "فشل التحقق من المصادقة",
  "Sync recovery queue": "طابور استعادة المزامنة",
  "Retry sync": "إعادة محاولة المزامنة",
  "Use existing account": "استخدام حساب موجود",
  "Local cache": "التخزين المحلي",
  "Start patient assessment": "بدء تقييم مريض",
  "Clinical workspace": "مساحة العمل السريرية",
  "Active patients": "المرضى النشطون",
  "Open interventions": "التدخلات المفتوحة",
  "Copilot cases": "حالات المساعد السريري",
  "Learning progress": "تقدم التعلم",
  "Search patients, cases...": "البحث عن المرضى والحالات...",
  "Your clinical workspace is ready. Review priority issues, continue your copilot cases, and keep every recommendation traceable to its evidence.": "مساحة العمل السريرية جاهزة. راجع الأولويات، وواصل حالات المساعد، واجعل كل توصية قابلة للتتبع إلى دليلها.",
  "Evidence source": "مصدر الدليل",
  "Evidence level": "مستوى الدليل",
  "Patient ID": "معرّف المريض",
  "Save review": "حفظ المراجعة",
  "Generate SOAP note": "إنشاء ملاحظة SOAP",
  "Create cloud case": "إنشاء حالة سحابية",
  "Safety alert": "تنبيه سلامة",
  "Review alert center": "مراجعة مركز التنبيهات",
  "No recommendation can be finalized without a verifiable guideline, regulatory source, or high-quality evidence reference.": "لا يمكن اعتماد التوصية دون إرشاد قابل للتحقق أو مصدر تنظيمي أو مرجع عالي الجودة.",
  "Patient assessment": "تقييم المريض",
  "Chief complaint": "الشكوى الرئيسية",
  "Allergies": "الحساسيات",
  "Current therapy": "العلاج الحالي",
  "Reason for admission": "سبب الدخول",
  "Document allergies or NKDA": "وثّق الحساسية أو اكتب لا توجد حساسية معروفة",
  "Medication, dose, route, frequency...": "الدواء والجرعة والطريق والتكرار...",
  "Evidence gate": "بوابة الدليل",
  "Source title or DOI / URL": "عنوان المصدر أو DOI / الرابط",
  "Evidence level e.g. A, B, guideline": "مستوى الدليل، مثل A أو B أو إرشاد",
  "Source verified for review": "تم التحقق من المصدر للمراجعة",
  "Insufficient evidence — source required": "دليل غير كافٍ — يلزم مصدر",
  "HIGH-RISK CLINICAL DECISION": "قرار سريري عالي الخطورة",
  "Verify the original source and institutional protocol before accepting this recommendation.": "تحقق من المصدر الأصلي والبروتوكول المؤسسي قبل قبول هذه التوصية.",
  "I confirm source verification is required": "أؤكد ضرورة التحقق من المصدر",
  "Pre-completion review": "مراجعة ما قبل الإكمال",
  "Clinical context": "السياق السريري",
  "Not documented": "غير موثق",
  "Missing source": "المصدر مفقود",
  "Insufficient evidence": "دليل غير كافٍ",
  Previous: "السابق",
  "Save patient draft": "حفظ مسودة المريض",
  Complete: "إكمال",
  Continue: "متابعة",
};

export function uiCopy(text: string) {
  if (typeof document === "undefined" || document.documentElement.dir !== "rtl") return text;
  return arabicCopy[text] ?? text;
}
