import { useMemo, useState } from "react";
import { AlertTriangle, BookOpen, Calculator, CheckCircle2, FileText, FlaskConical, GitCompare, GraduationCap, History, Plus, Search, ShieldAlert, Stethoscope } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { buildSoapNote, evidenceGate, hepaticDoseAdjustment, recordCalculation, renalDoseAdjustment, trainingTracks } from "@/lib/clinical-engine";

const guidelineRows = [
  { organization: "KDIGO", title: "CKD Evaluation & Management", year: "2024", tier: "Tier 1", status: "UPDATED", url: "https://kdigo.org/guidelines/ckd-evaluation-and-management/" },
  { organization: "ADA", title: "Standards of Care in Diabetes", year: "2025", tier: "Tier 1", status: "CURRENT", url: "https://diabetesjournals.org/care/issue/48/Supplement_1" },
  { organization: "FDA", title: "Official Drug Safety Communications", year: "2025", tier: "Tier 2", status: "CURRENT", url: "https://www.fda.gov/drugs/drug-safety-and-availability" },
];

export default function WorkspaceFeature({ activeModule }: { activeModule: string }) {
  const [dose, setDose] = useState("100");
  const [egfr, setEgfr] = useState("35");
  const [query, setQuery] = useState("");
  const [soapSaved, setSoapSaved] = useState(false);
  const [soapNote, setSoapNote] = useState("");
  const [childPugh, setChildPugh] = useState<"A" | "B" | "C">("B");
  const [history, setHistory] = useState<Array<{ type: string; value: string; timestamp: number }>>([]);
  const [homeMed, setHomeMed] = useState("metformin 500 mg BID");
  const [inpatientMed, setInpatientMed] = useState("lisinopril 10 mg daily");
  const adjusted = renalDoseAdjustment(Number(dose) || 0, Number(egfr) || 0);
  const hepatic = hepaticDoseAdjustment(Number(dose) || 0, childPugh);
  const filteredGuidelines = useMemo(() => guidelineRows.filter((row) => `${row.organization} ${row.title}`.toLowerCase().includes(query.toLowerCase())), [query]);

  if (!["Drug information", "Calculators", "Guidelines", "Training hub", "Clinical logbook", "Cases", "Questions", "Progress", "Alerts", "Interventions", "Reconciliation"].includes(activeModule)) return null;

  return <div className="mb-8 grid gap-6 xl:grid-cols-[1.4fr_0.8fr]">
    {(activeModule === "Guidelines" || activeModule === "Drug information") && <Card className="border-slate-200 shadow-sm"><CardHeader><div className="flex items-start justify-between gap-4"><div><p className="eyebrow">Evidence center</p><CardTitle className="mt-1 flex items-center gap-2"><BookOpen className="h-5 w-5 text-teal-700" />Guideline finder & comparison</CardTitle></div><Badge className="border-0 bg-[#eaf7f2] text-teal-800">Traceable sources</Badge></div><div className="relative mt-4"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search organization or guideline" className="pl-9" aria-label="Search evidence sources" /></div></CardHeader><CardContent className="space-y-3">{filteredGuidelines.map((row) => <div key={row.title} className="rounded-xl border border-slate-200 p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider text-teal-700">{row.organization} · {row.tier}</p><p className="mt-1 text-sm font-bold text-slate-800">{row.title}</p><p className="mt-1 text-xs text-slate-500">Publication year: {row.year} · Version status: {row.status}</p></div><GitCompare className="h-4 w-4 text-slate-400" /></div><a className="mt-3 inline-block text-xs font-bold text-teal-700 underline" href={row.url} target="_blank" rel="noreferrer">Open original source</a></div>)}{filteredGuidelines.length === 0 && <p className="py-5 text-sm text-slate-500">Insufficient evidence / source not available.</p>}</CardContent></Card>}

    {activeModule === "Calculators" && <Card className="border-slate-200 shadow-sm"><CardHeader><p className="eyebrow">Clinical calculators</p><CardTitle className="flex items-center gap-2"><Calculator className="h-5 w-5 text-teal-700" />Renal dose adjustment</CardTitle></CardHeader><CardContent><div className="grid gap-4 sm:grid-cols-2"><label className="field-label">Current dose (mg)<Input value={dose} onChange={(event) => setDose(event.target.value)} inputMode="decimal" /></label><label className="field-label">eGFR / CrCl<Input value={egfr} onChange={(event) => setEgfr(event.target.value)} inputMode="decimal" /></label></div><div className="mt-5 rounded-xl bg-[#eaf7f2] p-4"><p className="text-xs font-bold uppercase tracking-wider text-teal-800">Suggested review output</p><p className="mt-2 font-display text-3xl font-bold text-slate-900">{adjusted.doseMg} mg</p><p className="mt-1 text-sm text-slate-600">{adjusted.interval} · {adjusted.rationale}</p></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-xl border border-slate-200 bg-white p-3"><p className="text-xs font-bold text-slate-600">Hepatic adjustment</p><select value={childPugh} onChange={(event) => setChildPugh(event.target.value as "A" | "B" | "C")} className="mt-2 h-9 w-full rounded-lg border border-slate-200 px-2 text-sm" aria-label="Child Pugh class"><option value="A">Child-Pugh A</option><option value="B">Child-Pugh B</option><option value="C">Child-Pugh C</option></select><p className="mt-2 text-xs text-slate-500">Review dose: {hepatic.doseMg} mg</p></div><div className="rounded-xl border border-slate-200 bg-white p-3"><p className="text-xs font-bold text-slate-600">Calculation history</p><p className="mt-2 text-sm font-bold">{history.length} saved checks</p><Button onClick={() => setHistory((items) => recordCalculation(items, "renal + hepatic", `${adjusted.doseMg} mg / ${hepatic.doseMg} mg`))} variant="outline" className="mt-2 h-8 rounded-lg text-xs">Save calculation</Button></div></div></CardContent></Card>}

    {(activeModule === "Interventions" || activeModule === "Clinical logbook") && <Card className="border-slate-200 shadow-sm"><CardHeader><p className="eyebrow">Clinical documentation</p><CardTitle className="flex items-center gap-2"><FileText className="h-5 w-5 text-teal-700" />SOAP note & intervention log</CardTitle></CardHeader><CardContent><div className="grid gap-3 sm:grid-cols-2"><textarea className="min-h-24 rounded-xl border border-slate-200 p-3 text-sm" placeholder="Subjective" aria-label="Subjective note" /><textarea className="min-h-24 rounded-xl border border-slate-200 p-3 text-sm" placeholder="Objective" aria-label="Objective note" /><textarea className="min-h-24 rounded-xl border border-slate-200 p-3 text-sm" placeholder="Assessment" aria-label="Assessment note" /><textarea className="min-h-24 rounded-xl border border-slate-200 p-3 text-sm" placeholder="Plan and monitoring" aria-label="Plan note" /></div><div className="mt-4 flex items-center justify-between rounded-xl bg-slate-50 p-3"><p className="text-xs text-slate-500">Evidence must be linked before finalizing.</p><Button onClick={() => { setSoapNote(buildSoapNote({ subjective: "Clinical concern documented", objective: "Medication and laboratory data reviewed", assessment: "Pharmacotherapy requires follow-up", plan: "Monitor response and safety parameters", source: evidenceGate("https://example.org/source", "Guideline") ? "Verified guideline source" : undefined })); setSoapSaved(true); }} className="rounded-xl bg-[#102b2c] text-white">{soapSaved ? "Saved to logbook" : "Generate SOAP note"}</Button></div></CardContent></Card>}

    {(activeModule === "Training hub" || activeModule === "Cases" || activeModule === "Questions" || activeModule === "Progress") && <Card className="border-slate-200 shadow-sm"><CardHeader><p className="eyebrow">Student training</p><CardTitle className="flex items-center gap-2"><GraduationCap className="h-5 w-5 text-teal-700" />Adaptive therapeutics program</CardTitle></CardHeader><CardContent className="space-y-3">{trainingTracks.map((track) => <div key={track.title} className="rounded-xl border border-slate-200 p-4"><div className="flex items-center justify-between"><p className="text-sm font-bold text-slate-800">{track.title}</p><span className="text-xs font-bold text-teal-700">{track.progress}%</span></div><div className="mt-3 h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-teal-600" style={{ width: `${track.progress}%` }} /></div><div className="mt-3 flex gap-4 text-xs text-slate-500"><span>{track.cases} cases</span><span>{track.questions} questions</span><span>OSCE-ready pathway</span></div></div>)}</CardContent></Card>}

    {activeModule === "Alerts" && <Card className="border-rose-200 bg-rose-50/50 shadow-sm"><CardHeader><p className="eyebrow text-rose-700">Safety center</p><CardTitle className="flex items-center gap-2 text-rose-900"><ShieldAlert className="h-5 w-5 text-rose-600" />Actionable clinical alerts</CardTitle></CardHeader><CardContent className="space-y-3"><div className="rounded-xl border border-rose-200 bg-white p-4"><div className="flex gap-3"><AlertTriangle className="h-5 w-5 shrink-0 text-rose-600" /><div><p className="text-sm font-bold">High-alert therapy requires verification</p><p className="mt-1 text-xs leading-5 text-slate-500">Independent double-check, monitoring plan, and original source verification are required.</p><Button className="mt-3 rounded-xl bg-rose-600 text-white hover:bg-rose-700">Acknowledge & review</Button></div></div></div><div className="rounded-xl border border-amber-200 bg-white p-4"><p className="text-sm font-bold text-amber-900">Dose threshold alert</p><p className="mt-1 text-xs text-slate-500">The dose calculator flags renal adjustment when CrCl is below the configured threshold.</p></div></CardContent></Card>}

    {activeModule === "Reconciliation" && <Card className="border-slate-200 shadow-sm"><CardHeader><p className="eyebrow">Medication reconciliation</p><CardTitle className="flex items-center gap-2"><FlaskConical className="h-5 w-5 text-teal-700" />Admission / discharge comparison</CardTitle></CardHeader><CardContent><div className="grid gap-4 sm:grid-cols-2"><label className="field-label">Home medication list<textarea value={homeMed} onChange={(event) => setHomeMed(event.target.value)} className="min-h-28 rounded-xl border border-slate-200 p-3 text-sm" aria-label="Home medication list" /></label><label className="field-label">Current orders<textarea value={inpatientMed} onChange={(event) => setInpatientMed(event.target.value)} className="min-h-28 rounded-xl border border-slate-200 p-3 text-sm" aria-label="Current inpatient orders" /></label></div><div className="mt-4 rounded-xl bg-slate-50 p-4"><p className="text-sm font-bold">Review outcome</p><p className="mt-1 text-xs text-slate-500">Compare lists, document intentional omissions, and escalate unintentional discrepancies.</p><Button variant="outline" className="mt-3 rounded-xl"><CheckCircle2 className="mr-2 h-4 w-4" />Mark reconciliation reviewed</Button></div></CardContent></Card>}

    <Card className="border-slate-200 bg-white shadow-sm"><CardHeader><p className="eyebrow">Clinical governance</p><CardTitle className="flex items-center gap-2"><ShieldAlert className="h-5 w-5 text-teal-700" />Safety and evidence controls</CardTitle></CardHeader><CardContent className="space-y-3 text-sm text-slate-600"><p className="flex gap-2"><CheckCircle2 className="h-4 w-4 shrink-0 text-teal-700" />Every final recommendation must have a source URL and evidence level.</p><p className="flex gap-2"><CheckCircle2 className="h-4 w-4 shrink-0 text-teal-700" />High-risk decisions require original-source verification.</p><p className="flex gap-2"><CheckCircle2 className="h-4 w-4 shrink-0 text-teal-700" />When no suitable evidence is available, the system displays Insufficient evidence.</p></CardContent></Card>
  </div>;
}
